sculpin:
    source_dir: www/
    output_dir: build/
    permalink: none # no pretty permalink (keep talks.html instead of talks/index.html)

sculpin_content_types:
    posts:
        permalink: :year/:slug_filename.html

    # we don't really want to render this as an individual page, but we kind of have to…
    talks:
        permalink: .ignoreme.html # (over)write all talks to dummy file
        layout: default # use simple dummy template
        taxonomies:
            - tags
