name: CI

on:
  push:
  pull_request:

jobs:
  Acceptance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: 
          - 7.2
          - 7.3
          - 7.4
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer install
      - run: vendor/bin/sculpin generate
      - run: docker run -d -p 8080:80 -v "$PWD"/build:/var/www/html php:7.4-apache sh -c "ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled; apache2-foreground"
      - run: tests/acceptance.sh http://localhost:8080
